In [1]:
# 미세먼지 데이터
pm10_data = [500, 29, 29, 155, 29, 29, 29, 42, 201, 42, 42, 22, 42, 29, 29, 99, 29, 29, 
29, 150, 165, 268, 263, 258, 254, 254, 191, 121, 45, 89, 76, 32, 78, 98, 11, 24, 53,78, 
94]

# 초미세먼지 데이터
pm25_data = [295, 115, 111, 108, 168, 155, 147, 140, 130, 125, 160, 111, 99, 105, 88, 
65, 145, 156, 152, 104, 104, 104, 59, 103, 103, 33,  165, 268, 263, 258, 254, 254, 191, 
221, 178]

In [2]:
import pandas as pd

In [3]:
pm10 = pd.Series(pm10_data)
pm10

0     500
1      29
2      29
3     155
4      29
5      29
6      29
7      42
8     201
9      42
10     42
11     22
12     42
13     29
14     29
15     99
16     29
17     29
18     29
19    150
20    165
21    268
22    263
23    258
24    254
25    254
26    191
27    121
28     45
29     89
30     76
31     32
32     78
33     98
34     11
35     24
36     53
37     78
38     94
dtype: int64

In [4]:
pm25 = pd.Series(pm25_data)
pm25

0     295
1     115
2     111
3     108
4     168
5     155
6     147
7     140
8     130
9     125
10    160
11    111
12     99
13    105
14     88
15     65
16    145
17    156
18    152
19    104
20    104
21    104
22     59
23    103
24    103
25     33
26    165
27    268
28    263
29    258
30    254
31    254
32    191
33    221
34    178
dtype: int64

In [5]:
df = pd.DataFrame({
    "미세먼지pm10":pm10,
    "미세먼지pm25":pm25
})

In [6]:
df.head()

   미세먼지pm10  미세먼지pm25
0       500     295.0
1        29     115.0
2        29     111.0
3       155     108.0
4        29     168.0

In [9]:
df.info

<bound method DataFrame.info of     미세먼지pm10  미세먼지pm25
0        500     295.0
1         29     115.0
2         29     111.0
3        155     108.0
4         29     168.0
5         29     155.0
6         29     147.0
7         42     140.0
8        201     130.0
9         42     125.0
10        42     160.0
11        22     111.0
12        42      99.0
13        29     105.0
14        29      88.0
15        99      65.0
16        29     145.0
17        29     156.0
18        29     152.0
19       150     104.0
20       165     104.0
21       268     104.0
22       263      59.0
23       258     103.0
24       254     103.0
25       254      33.0
26       191     165.0
27       121     268.0
28        45     263.0
29        89     258.0
30        76     254.0
31        32     254.0
32        78     191.0
33        98     221.0
34        11     178.0
35        24       NaN
36        53       NaN
37        78       NaN
38        94       NaN>

In [10]:
df.describe() # 숫자형 기본 # 요약 통계

         미세먼지pm10    미세먼지pm25
count   39.000000   35.000000
mean   103.512821  149.628571
std    103.947323   65.270967
min     11.000000   33.000000
25%     29.000000  104.000000
50%     53.000000  140.000000
75%    152.500000  173.000000
max    500.000000  295.000000

In [11]:
df.isnull().sum() # 컬럼별 결측치

미세먼지pm10    0
미세먼지pm25    4
dtype: int64

In [12]:
df.isnull()

    미세먼지pm10  미세먼지pm25
0      False     False
1      False     False
2      False     False
3      False     False
4      False     False
5      False     False
6      False     False
7      False     False
8      False     False
9      False     False
10     False     False
11     False     False
12     False     False
13     False     False
14     False     False
15     False     False
16     False     False
17     False     False
18     False     False
19     False     False
20     False     False
21     False     False
22     False     False
23     False     False
24     False     False
25     False     False
26     False     False
27     False     False
28     False     False
29     False     False
30     False     False
31     False     False
32     False     False
33     False     False
34     False     False
35     False      True
36     False      True
37     False      True
38     False      True

In [13]:
df.isnull().sum().sum() # 전체 데이터프레임의 결측치 수

np.int64(4)

In [14]:
df.duplicated().sum() # 중복 행 수

np.int64(0)

In [15]:
# 미세먼지 pm2.5의 평균
df["미세먼지pm25"].mean()

np.float64(149.62857142857143)

In [16]:
# 결측치를 채운다 - fillna()

df["미세먼지pm25"].fillna(0) # 결측치를 0으로 채운다.

0     295.0
1     115.0
2     111.0
3     108.0
4     168.0
5     155.0
6     147.0
7     140.0
8     130.0
9     125.0
10    160.0
11    111.0
12     99.0
13    105.0
14     88.0
15     65.0
16    145.0
17    156.0
18    152.0
19    104.0
20    104.0
21    104.0
22     59.0
23    103.0
24    103.0
25     33.0
26    165.0
27    268.0
28    263.0
29    258.0
30    254.0
31    254.0
32    191.0
33    221.0
34    178.0
35      0.0
36      0.0
37      0.0
38      0.0
Name: 미세먼지pm25, dtype: float64

In [17]:
df["미세먼지pm25"].fillna(df["미세먼지pm25"].mean()) # 결측치를 평균으로 채운다.

0     295.000000
1     115.000000
2     111.000000
3     108.000000
4     168.000000
5     155.000000
6     147.000000
7     140.000000
8     130.000000
9     125.000000
10    160.000000
11    111.000000
12     99.000000
13    105.000000
14     88.000000
15     65.000000
16    145.000000
17    156.000000
18    152.000000
19    104.000000
20    104.000000
21    104.000000
22     59.000000
23    103.000000
24    103.000000
25     33.000000
26    165.000000
27    268.000000
28    263.000000
29    258.000000
30    254.000000
31    254.000000
32    191.000000
33    221.000000
34    178.000000
35    149.628571
36    149.628571
37    149.628571
38    149.628571
Name: 미세먼지pm25, dtype: float64

In [18]:
df

    미세먼지pm10  미세먼지pm25
0        500     295.0
1         29     115.0
2         29     111.0
3        155     108.0
4         29     168.0
5         29     155.0
6         29     147.0
7         42     140.0
8        201     130.0
9         42     125.0
10        42     160.0
11        22     111.0
12        42      99.0
13        29     105.0
14        29      88.0
15        99      65.0
16        29     145.0
17        29     156.0
18        29     152.0
19       150     104.0
20       165     104.0
21       268     104.0
22       263      59.0
23       258     103.0
24       254     103.0
25       254      33.0
26       191     165.0
27       121     268.0
28        45     263.0
29        89     258.0
30        76     254.0
31        32     254.0
32        78     191.0
33        98     221.0
34        11     178.0
35        24       NaN
36        53       NaN
37        78       NaN
38        94       NaN

In [19]:
df["미세먼지pm25"] = df["미세먼지pm25"].fillna(df["미세먼지pm25"].mean())

In [20]:
df

    미세먼지pm10    미세먼지pm25
0        500  295.000000
1         29  115.000000
2         29  111.000000
3        155  108.000000
4         29  168.000000
5         29  155.000000
6         29  147.000000
7         42  140.000000
8        201  130.000000
9         42  125.000000
10        42  160.000000
11        22  111.000000
12        42   99.000000
13        29  105.000000
14        29   88.000000
15        99   65.000000
16        29  145.000000
17        29  156.000000
18        29  152.000000
19       150  104.000000
20       165  104.000000
21       268  104.000000
22       263   59.000000
23       258  103.000000
24       254  103.000000
25       254   33.000000
26       191  165.000000
27       121  268.000000
28        45  263.000000
29        89  258.000000
30        76  254.000000
31        32  254.000000
32        78  191.000000
33        98  221.000000
34        11  178.000000
35        24  149.628571
36        53  149.628571
37        78  149.628571
38        94  149.628571

In [21]:
# 미세먼지 10 1사분위수 (Q1)
q1 = df["미세먼지pm10"].quantile(.25)

# 미세먼지 10 3사분위수 (Q3)
q3 = df["미세먼지pm10"].quantile(.75)

q1, q3

(np.float64(29.0), np.float64(152.5))

In [23]:
# iqr -> q3 - q1
iqr = q3 - q1

iqr

np.float64(123.5)

In [24]:
# 하한(최소값)
lower = q1 - 1.5 * iqr

lower

np.float64(-156.25)

In [25]:
# 상한(최소값)
upper = q3 + 1.5 * iqr

upper

np.float64(337.75)

In [27]:
# 이상치
outliers = df[(df["미세먼지pm10"] < lower) | (df["미세먼지pm10"] > upper)]

outliers

   미세먼지pm10  미세먼지pm25
0       500     295.0